char LOTS_BLURB_FILE [200];

int LOTRACE_VAR_POLYORDER_LO			= 1;
int LOTRACE_VAR_POLYORDER_HI			= 10;

char LOTRACE_VAR_ACCURACY_COEFFS [10]		= "%.10e";
char LOTRACE_VAR_ACCURACY_CHISQ [10]		= "%.2f";

double LOTRACE_VAR_CHISQUARED_MIN		= 0.1;
double LOTRACE_VAR_CHISQUARED_MAX		= 10;

char LOTRACE_OUTPUTF_TRACES_FILE [100] 		= "lotrace_traces.dat";


